class FileName:
    calibration_data = "calibration_data.json"
    coordinates_data = "coordinates_data.json"
    world_coordinates_data = "world_coordinates_data.json"
    world_coordinates_relative_data = "world_coordinates_relative_data.json"
    solve_pnp_data = "solve_pnp_data.json"
    fundamental_matrix_data = "fundamental_matrix_data.json"
    optimized_data = "optimized_data.json"
    optimized_world_coordinates_data = "optimized_world_coordinates_data.json"
    position_data = "position_data.csv"
    visibility_data = "visibility_data.csv"
    tracking_data = "tracking_data.csv"
    output_video = "output.mp4"
    threed_motion = "3d_motion.html"
    threed_position = "3d_position_data.csv"
    px_subsets = "px_subsets.json"