keypoints_list = [
    'RWRL',
    'RWRM',
    'RELL',
    'RELM',
    'RSHF',
    'RSHB',
    'LWRL',
    'LWRM',
    'LELL',
    'LELM',
    'LSHF',
    'LSHB',
    'RANL',
    'RANM',
    'RKNL',
    'RKNM',
    'RTRO',
    'LANL',
    'LANM',
    'LKNL',
    'LKNM',
    'LTRO',
    'REAR',
    'LEAR'
]

exp_keypoints_list = [
    "NOSE",
    "LEFT_EYE",
    "RIGHT_EYE",
    "LEFT_EAR",
    "RIGHT_EAR",
    "LEFT_SHOULDER",
    "RIGHT_SHOULDER",
    "LEFT_ELBOW",
    "RIGHT_ELBOW",
    "LEFT_WRIST",
    "RIGHT_WRIST",
    "LEFT_HIP",
    "RIGHT_HIP",
    "LEFT_KNEE",
    "RIGHT_KNEE",
    "LEFT_ANKLE",
    "RIGHT_ANKLE"
]

exp_keypoints_connections = {
    "NOSE_LEFT_EYE": [0, 1],
    "NOSE_RIGHT_EYE": [0, 2],
    "LEFT_EYE_EAR": [1, 3],
    "RIGHT_EYE_EAR": [2, 4],
    "SHOULDER": [5, 6],
    "LEFT_UPPER_ARM": [5, 7],
    "RIGHT_UPPER_ARM": [6, 8],
    "LEFT_FORE_ARM": [7, 9],
    "RIGHT_FORE_ARM": [8, 10],
    "LEFT_TORSO": [5, 11],
    "RIGHT_TORSO": [6, 12],
    "GROIN": [11, 12],
    "LEFT_THIGH": [11, 13],
    "RIGHT_THIGH": [12, 14],
    "LEFT_LOWER_LEG": [13, 15],
    "RIGHT_LOWER_LEG": [14, 16],
}